import { describe, it, expect } from "vitest";
import { legalMoves, getWinner, State, Move } from "@/lib/ai/engine";
import { encodeState } from "@/lib/ai/encode";
import fixtures from "./ai-fixtures.json";

// Cross-language parity: every fixture is generated by the canonical Python
// engine (backend/gen_test_fixtures.py). The TypeScript port must reproduce its
// encoding, legal moves, and winner exactly — otherwise the in-browser AI would
// silently diverge from the trained model.

interface Fixture {
  state: {
    boards: (string | null)[][];
    boardWinners: (string | null)[];
    activeBoard: number | null;
    player: "X" | "O";
  };
  encoded: number[];
  legalMoves: number[][];
  winner: string | null;
}

function toState(f: Fixture["state"]): State {
  return {
    boards: f.boards as State["boards"],
    winners: f.boardWinners as State["winners"],
    active: f.activeBoard,
    player: f.player,
  };
}

describe("engine/encode parity with Python backend", () => {
  const cases = fixtures as Fixture[];

  it("has fixtures to check", () => {
    expect(cases.length).toBeGreaterThan(10);
  });

  cases.forEach((f, i) => {
    const state = toState(f.state);

    it(`fixture ${i}: encodeState matches (486 floats)`, () => {
      const enc = encodeState(state);
      expect(enc.length).toBe(f.encoded.length);
      for (let k = 0; k < enc.length; k++) {
        expect(enc[k]).toBe(f.encoded[k]);
      }
    });

    it(`fixture ${i}: legalMoves match (order-sensitive)`, () => {
      const moves = legalMoves(state).map((m: Move) => [m[0], m[1]]);
      expect(moves).toEqual(f.legalMoves);
    });

    it(`fixture ${i}: winner matches`, () => {
      expect(getWinner(state)).toBe(f.winner);
    });
  });
});
