import { describe, it, expect } from "vitest";
import { encodeStateV2, INPUT_DIM_V2 } from "@/lib/ai/encode";
import { State } from "@/lib/ai/engine";
import fixtures from "./ai-fixtures.json";

// Cross-language parity for the 11-plane v2 encoding: the TypeScript
// encodeStateV2 must reproduce backend/net.encode_state_v2 exactly (the
// `encoded_v2` field is generated by backend/gen_test_fixtures.py).

interface Fixture {
  state: {
    boards: (string | null)[][];
    boardWinners: (string | null)[];
    activeBoard: number | null;
    player: "X" | "O";
  };
  encoded_v2: number[];
}

function toState(f: Fixture["state"]): State {
  return {
    boards: f.boards as State["boards"],
    winners: f.boardWinners as State["winners"],
    active: f.activeBoard,
    player: f.player,
  };
}

describe("v2 (11-plane) encode parity with Python backend", () => {
  const cases = fixtures as Fixture[];

  it("fixtures carry v2 encodings of the right size", () => {
    expect(cases.length).toBeGreaterThan(10);
    expect(cases[0].encoded_v2.length).toBe(INPUT_DIM_V2);
  });

  cases.forEach((f, i) => {
    it(`fixture ${i}: encodeStateV2 matches (891 floats)`, () => {
      const enc = encodeStateV2(toState(f.state));
      expect(enc.length).toBe(f.encoded_v2.length);
      for (let k = 0; k < enc.length; k++) {
        expect(enc[k]).toBe(f.encoded_v2[k]);
      }
    });
  });
});
